language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
# need "install ." to install resync so that client tests work
install:
  - pip install .
  - pip install requests
  - pip install python-dateutil
# command to run tests
script: py.test
